In [13]:
from pathlib import Path, PosixPath

def get_files(csv_path: str) -> list:
    path_ = Path(csv_path)
    if not path_.exists():
        print(f"Directory '{csv_path}' does not exist.")
        return []
    files = list(path_.glob('*.csv'))
    if not files:
        print(f"No .csv files found in '{csv_path}'.")
    return files

def get_backend_ds_name(c: PosixPath) -> tuple:
    parts = c.name.split('__')
    ds_name = parts[0].replace("rows_", "")
    backend_name = parts[1]
    return ds_name, backend_name

In [15]:
import pandas as pd

csv_files = get_files("lambda_grid_results/coarse")
for c in csv_files:
    ds_name, backend_name = get_backend_ds_name(c)
    print("-" * 50, ds_name, "-", backend_name, "-" * 50)
    df600 = pd.read_csv(c).head(600)
    print(df600.groupby(["lambda1", "lambda2", "lambda3"])[
        ["validity","prox_cont_mad_negmean","div_cont_mad","robustness_keep_rate"]
    ].mean().describe(), "\n")

-------------------------------------------------- compas-recidivism - sklearn --------------------------------------------------
       robustness_keep_rate
count            120.000000
mean               0.781103
std                0.087041
min                0.566667
25%                0.722222
50%                0.766667
75%                0.855556
max                0.962963 

-------------------------------------------------- compas-recidivism - PYT --------------------------------------------------
       validity  prox_cont_mad_negmean  div_cont_mad  robustness_keep_rate
count       0.0             120.000000    120.000000            120.000000
mean        NaN              -3.450904      3.429050              0.901111
std         NaN               0.203419      0.571763              0.031539
min         NaN              -3.747262      0.000000              0.800000
25%         NaN              -3.525595      3.451190              0.911111
50%         NaN              -3.443214  

/var/folders/8m/6z48y8212x782rk9dpgmm9lm0000gn/T/ipykernel_41635/2481558721.py:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ].mean().describe(), "\n")


In [19]:
import numpy as np

# 1. Create a default random number generator
rng = np.random.default_rng()

# 2. Use the generator to create random numbers

# Generate 5 random floats between 0.0 and 1.0
random_floats = rng.random((5,5))
print(f"Random floats:\n{random_floats}\n")

# Generate a 2x3 array of random integers between 0 and 9 (exclusive of 10)
random_integers = rng.integers(low=0, high=10, size=(2, 3))
print(f"Random integers:\n{random_integers}\n")

# Generate 4 numbers from a standard normal distribution (mean=0, std=1)
normal_dist_numbers = rng.standard_normal(4)
print(f"Numbers from a normal distribution:\n{normal_dist_numbers}")

Random floats:
[[0.3419868  0.95974155 0.34271054 0.19383558 0.32830435]
 [0.42365655 0.31024846 0.49645013 0.54068712 0.00309475]
 [0.37987423 0.27144291 0.95026764 0.15437906 0.16587382]
 [0.77312895 0.12777491 0.32019838 0.65577865 0.37358289]
 [0.64434267 0.90568311 0.45399058 0.42188925 0.41415518]]

Random integers:
[[5 0 7]
 [1 4 0]]

Numbers from a normal distribution:
[0.383225   1.13207925 0.74789829 1.15411382]
